---
dependency:
  name: galaxy
  options:
    requirements-file: meta/requirements.yml
lint: |
  set -e
  yamllint -c tests/yamllint.cfg .
  ansible-lint -c tests/ansible-lint.yml .
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance-localhost
provisioner:
  name: ansible
  options:
    vv: true
    become: true
  inventory:
    links:
      group_vars: ../../tests/inventory/group_vars
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
