---
dependency:
  name: galaxy
  options:
    requirements-file: meta/requirements.yml
lint: |
  set -e
  yamllint -c tests/yamllint.cfg .
  ansible-lint -c tests/ansible-lint.yml .
driver:
  name: podman
# https://molecule.readthedocs.io/en/latest/examples.html#systemd-container
platforms:
  - name: instance
    image: docker.io/fedora:latest
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  inventory:
    links:
      group_vars: ../../tests/inventory/group_vars
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
